server:
  port: 9091
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: account
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3036/account
    username: root
    password: springbootpsw

security:
  ouath2:
    resource:
      jwt:
        key-value: productKey
